### ISSUE TITLE
Bug na visualização no iOS

### ISSUE THREAD

**Issue by esasse** [ruby-jobs/ruby-jobs#11]
Nada muito importante.

![img_0491](https://cloud.githubusercontent.com/assets/148989/5930699/4aac69d4-a67a-11e4-8fe3-be9f5e79de77.PNG)

**Comment by Brunozrk** [comment]
Acho que está acontecendo com todas telas pequenas

**Comment by lucasnogueira** [comment]
A home acho que está arrumada, só falta a outra tela de `jobs`.

**Comment by esasse** [comment]
Confirmo que o problema que eu reportei nesta issue está resolvido.
