### ISSUE TITLE
Data para expiração para a vaga

### ISSUE THREAD

**Issue by luizpicolo** [ruby-jobs/ruby-jobs#20]
Seria interessante uma data limite para as vagas, ou seja, não necessáriamente todas as vagas seriam mostras no site, mas somente as que tiveram sua data limite válida.

**Comment by matheusml** [comment]
Então, nós avisamos, no momento de criação de uma vaga nova, que ela tem no máximo 3 meses de duração.

**Comment by luizpicolo** [comment]
Então, mas isso não é algo visível para o candidato. Tem vagas no site de Setembro de 2014 a qual, não há nada mostrando que esta desativada.
Acredito que uma verificação seria interessante.

http://www.rubyjobs.me/jobs/5-desenvolvedor-ruby-on-rails

**Comment by matheusml** [comment]
Isso acontece porque ainda não estamos deletando as vagas com mais de três meses.
Na prática o que vai acontecer no futuro é que somente as vagas criadas há menos de três meses aparecerão, então isso seria eliminado.

**Comment by luizpicolo** [comment]
Exatamente. Por este motivo abri esta discussão, para verificar se seria interessante eu adicionar essa funcionalidade.

**Comment by lccezinha** [comment]
@luizpicolo acho que o modo mais simples para o que temos agora seria apenas fazer um filtro trazendo os jobs que foram publicados dentro dos ultimos 3 meses, o que acha ?

**Comment by luizpicolo** [comment]
@lccezinha era isso que eu havia pensado. :+1:

**Comment by lccezinha** [comment]
show :+1:

**Comment by luizpicolo** [comment]
Okay, vou implementar essa funcionalidade e por para análise.

**Comment by lccezinha** [comment]
Se eu não me engano no PR #29 o @jmscarpa fez isso.

**Comment by lucianosousa** [comment]
Boa!

**Comment by luizpicolo** [comment]
:+1:  Boa!
