### ISSUE TITLE
Remover campo salário

### ISSUE THREAD

**Issue by matheusml** [ruby-jobs/ruby-jobs#21]
O campo não vem sendo usado.
Remover o campo ```salary``` e todas suas dependências/testes.

**Comment by lccezinha** [comment]
Vou fazer aqui ;)

**Comment by Brunozrk** [comment]
O uso não é frequente, mas tem uns que usam:

http://www.rubyjobs.me/jobs/91-desenvolvedor-back-end
end
http://www.rubyjobs.me/jobs/86-dev-rails-backend
http://www.rubyjobs.me/jobs/82-dev-ruby-pleno

**Comment by Brunozrk** [comment]
http://www.rubyjobs.me/jobs/94-lider-tecnico-ruby-on-rails
http://www.rubyjobs.me/jobs/93-desenvolvedor-ruby-on-rails

Acho melhor manter eim... Rsrs

O que acham?

**Comment by lccezinha** [comment]
Ow :hankey: HUAEHEA pois é.. se tem gente usando é melhor manter, EU particularmente curto quando vejo um anúncio com salário.

**Comment by Brunozrk** [comment]
Kkkkkk, eu tbm

**Comment by matheusml** [comment]
Desde que botamos a feature o uso foi muito pequeno.
E tem também casos de uso errado da feature como aqui:
http://www.rubyjobs.me/jobs/92-desenvolvedor-web-ruby-on-rails

**Comment by lccezinha** [comment]
Bom a feature tá ae.. fica a cargo de quem tem poder mergear ou não HAEIU

**Comment by matheusml** [comment]
Por enquanto são 2 contra 1, então vamos discutir mais. 
Uma coisa é certa, vamos começar a discutir as issues novas antes de começar a atacar.

**Comment by Brunozrk** [comment]
@matheusml, esse link ta com erro! :disappointed:

**Comment by esasse** [comment]
Foi adicionado há pouco tempo. Sugiro deixar mais um pouco.

**Comment by matheusml** [comment]
3 contra 1, vamos deixar mais tempo então. o/
E vamos tentar discutir mais antes da implementação.
