### ISSUE TITLE
Remover Gems não utilizadas no Gemfile

### ISSUE THREAD

**Issue by lccezinha** [ruby-jobs/ruby-jobs#24]
Olhando o `Gemfile` do projeto notei que existem algumas gems que não são usadas ou estão duplicadas.

Hoje na pasta de `spec` existem as pastas `factory_girl`, `fixtures` e `fabrication`. Sugiro remover as pastas de `fixtures` e `factory_girl` já que está sendo usado `fabrication` no spec. Por mim deixava só o `factory_girl` que já era usado.

Outra é o `capybara` que existem no `Gemfile` mas não são feitos os testes de features.

Eae, remover essas gems ou deixar para futuramente utilizar ?

**Comment by esasse** [comment]
Se não é utilizada tem que remover. Não é uma boa ideia deixar apenas para
um possível uso no futuro.

**Comment by matheusml** [comment]
@esasse +1
Assim como as duplicadas.

**Comment by Brunozrk** [comment]
+1, se não está usando, não precisa existir
Com relação ao `spec`, concordo em padronizar no `factory_girl`!

**Comment by lccezinha** [comment]
:+1:  também acho que deve remover e deixar no factory_girl, porém precisa arrumar os `specs` que estão usando `fabrication` .

**Comment by jmscarpa** [comment]
Nossa! Eu fiz um refactor das gems antes de ver essa issue haha. Vou abrir o PR

**Comment by lccezinha** [comment]
Show :+1:

**Comment by jmscarpa** [comment]
@lccezinha acabei de abrir o PR. se puder/quiser dar uma olhada. Não fiz a troca do fabrication pelo factory_girl. Acho que cabe uma issue pra isso. No momento só foi alterado algumas coisas no Gemfile mesmo.  PR #28
