### ISSUE TITLE
Possível monetização do RubyJobs

### ISSUE THREAD

**Issue by matheusml** [ruby-jobs/ruby-jobs#25]
Em uma discussão recente com o @jmscarpa rolou o papo sobre a monetização do RJ, visto que diversos outros sites no mesmo estilo do RJ cobram. Alguns inclusive, como o [https://weworkremotely.com/](https://weworkremotely.com/) chegam a cobrar US$200 por 30 dias.

Mas existem alguns problemas em relação a isso:
* Pessoas parando de usar a ferramenta
* Pessoas parando de contribuir com o projeto
* Pra quem vai o dinheiro?
* É legal um projeto open source receber o dinheiro?

Uma das propostas é deixar as vagas gratuitas durando 1 semana, enquanto as pagas duram 3 meses. E as funcionalidades são iguais para ambas.

Outra proposta seria deixar ambas durando 3 meses, só que as gratuitas a fonte será trocada para Comic Sans (parecido com o que o [https://chocolatapp.com/](https://chocolatapp.com/) faz).

Agora tem a questão do dinheiro também, o que eu pensei foi um pagamento único de algum valor entre R$49 e R$99 e esse dinheiro indo direto para alguma causa social.

**Comment by esasse** [comment]
Faz bem pouco tempo que estou "envolvido" com o projeto, então pode ser que
eu não tenha uma visão bem formada de tudo.

Pelo que conheci do projeto até agora, acho um pouco cedo para pensar
nisso. Quando envolve dinheiro acho que as coisas se complicam bastante.
Mesmo que seja apenas para causas sociais.

Ah não ser que alguém já tenha um esquema bem descomplicado para canalizar
dinheiro diretamente para uma instituição beneficente de confiança. Alguém
tem?

**Comment by jmscarpa** [comment]
Uma ideia que me ocorreu, é que esse dinheiro poderia ser usado para criar ou auxiliar grupos de rupy (como o GURU-SP) em diversas localidade. Gera engajamento, mídia para a plataforma e as empresas que anunciam acabam ganhando indiretamente porque sabe que os profissionais que verão as vagas são minimamente engajados.

**Comment by esasse** [comment]
Se a cobrança for obrigatória, você pode contar uma redução de no mínimo
90% nas publicações de vagas. Se for opcional, acho que menos de 10% vão
pagar.

Não sei bem a quantidade de vagas por mês que estão sendo publicadas, então
tem que ver se o custo/beneficio se justifica.

**Comment by matheusml** [comment]
Achei boa a ideia @jmscarpa 
O principal é achar uma forma de o dinheiro cair direto na conta dos beneficiários, sem que passe por nós.

@esasse O número não tenderá a diminuir se nós fizermos um modelo Fremium, ou seja ainda contando com uma modalidade gratuita, que irá possuir alguma(s) desvantagem(s)

**Comment by esasse** [comment]
👍

**Comment by lucasnogueira** [comment]
Acho a ideia muito interessante, mas não podemos deixar morrer.

A primeira parte seria mapear que features seriam criadas para quem quiser pagar para anunciar.

Quanto ao destino do dinheiro, creio que instituições de caridade seja um destino fantástico que talvez só incentive as pessoas a utilizar o serviço "premium".

**Comment by matheusml** [comment]
@lucasnogueira +1
Acho válido também levantar essa bola com a comunidade (talvez no facebook mesmo) e ver quais ideias eles tem.

**Comment by lucasfurtado** [comment]
Faz pouco tempo que acompanho o projeto, mas posso dar uma sugestão?

De inicio colocar na pagina inicial algo parecido como empresas que apoiam o projeto, por exemplo igual na pagina de eventos, dando um destaque para essas empresas.

**Comment by matheusml** [comment]
@lucasfurtado é uma boa mesmo. Como "patrocinadores".

**Comment by lucasnogueira** [comment]
Curti a ideia também. Mas seria como um subscription? Porque ganhar o
espaço fixo por ter pago uma vaga parece muito. Pode ter um tempo limite
também ou algo do gênero.
Em 06/04/2015 17:57, "Matheus Lima" <notifications@github.com> escreveu:

**Comment by Brunozrk** [comment]
Essa de empresas que apoiam o projeto acho uma boa, podemos evoluir pensando nisso!

**Comment by lucasfurtado** [comment]
Acho que de começo pode ser feito isso, apoiando somente o rubyjobs.

Se der certo, e como a ideia inicial é apoiar grupos de ruby, pode ser criado um bagde que os contratantes vão adquirindo caso comecem a apoiar um grupo, por exemplo "Esta empresa apoia o Guru-SP", ou mesmo eventos como "Esta empresa apoia o RuPy".

Assim evita de lidar com monetização direta, o incentivo vai ser direto ao grupo.
