### ISSUE TITLE
Melhoria na disposição do título da vaga

### ISSUE THREAD

**Issue by lucasnogueira** [ruby-jobs/ruby-jobs#27]
Tem um tempo que o espaço reservado para o título da vaga está me incomodando um pouco. Essas são as 5 primeiras vagas aparecendo hoje no site:

![rubyjobs-5-jobs](https://cloud.githubusercontent.com/assets/1480149/6341658/c3867d9a-bbab-11e4-837b-ac870587dd33.png)

No caso elas não dizem muita coisa, só que 4 são para desenvolvedores e 1 para líder técnico :smile: 

O primeiro passo seria alterar o `length` na `td`. Mas como isso envolveria o layout da principal tela e talvez outras pessoas tenham sugestões de ideias e mudanças, prefiro deixar aberto para opiniões. Existe também um outro [issue](https://github.com/ruby-jobs/ruby-jobs/issues/11) que acusa problemas de layout nessa tela em smartphones, então talvez 2 problemas sejam resolvidos de uma vez.

Quem quiser/puder implementar também, à vontade :wink:

**Comment by matheusml** [comment]
Que tal mudar de lugar o título da vaga com o nome da empresa?

**Comment by esasse** [comment]
Uma outra ideia seria colocar o nome da empresa abaixo do nome da vaga, permitindo que a vaga use todo o espaço até onde hoje está o nome da empresa.

**Comment by lucasnogueira** [comment]
Bem, alterei o layout com base nas ideias dadas. Como esse não é meu forte, sugestões são sempre bem vindas.

Não alterei a página do `/jobs` visto que não consegui utilizar o `truncate` com o angular. Talvez esse [filter](https://github.com/sparkalow/angular-truncate) resolva. Do jeito que está hoje, se alguém fizer um `job` gigante vai quebrar toda a tela.

Uma screenshot de como ficou:

![screen shot 2015-02-26 at 10 24 37 pm](https://cloud.githubusercontent.com/assets/1480149/6405757/4635e5d0-be06-11e4-8303-00e3cf767044.png)

**Comment by esasse** [comment]
Acho que estamos no caminho certo. Eu só reduziria um pouco o espaço vertical entre a descrição da vaga e o nome da empresa.

**Comment by matheusml** [comment]
#30
