### ISSUE TITLE
Discussão - Criar Job apenas autenticado

### ISSUE THREAD

**Issue by matheusml** [ruby-jobs/ruby-jobs#3]
Galera,
estou com a ideia de liberar a criação de novos jobs apenas com auth (pode ser linkedin e facebook, por exemplo). 
A motivação é eliminar os jobs fakes e também termos o perfil de quem está criando os jobs.
O lado negativo é a criação de uma barreira de entrada para novos usuários.
O que acham?

**Comment by lccezinha** [comment]
Acho que por hora ainda é melhor deixa livre, pois se o cara quer divulgar a vaga ele raramente irá querer se cadastrar somente para isso.

Muita gente vem e posta no facebook e nós indicamos eles pra cá, se todos eles tiverem que criar um cadastro pra postar a vaga acho que ficaria meio chato.

Uma alternativa seria ter uma interface admin onde alguem poderia ou não aprovar o Job (caso ele seja um fake) ou até mesmo depois de postado, eliminar o job.

**Comment by Brunozrk** [comment]
É, também acho que pode criar uma barreira :cry:. Acho que não deviamos deixar somente autenticados criar os jobs (pelo menos por enquanto).

@lccezinha, com relação ao aprovar e não aprovar, acho que não vai rolar agora também (https://github.com/matheusml/rubyjobs/issues/78)

Talvez pra **agora** fosse melhor criar o admin para ficar mais fácil apagar os jobs errados, ou fakes, etc.

**Outra ideia:** Podemos pensar em alguma vantagem pra quem é autenticado, mas não bloquear quem não é de postar jobs. Assim tentamos incentivar a galera a se cadastrar.

**Comment by matheusml** [comment]
Jobs não cadastrados duram 1 semana, enquanto os cadastrados duram 3 meses. Ou algo do tipo.

**Comment by Brunozrk** [comment]
:+1:  Isso, acho que é por ai! :fireworks:

**Comment by matheusml** [comment]
A gente tem um rake file (que nunca foi rodado, a propósito) que remove jobs criados após uma certa data. Nós poderíamos adicionar uma data para alterar esse rake, logo após a criação de uma tarefa com auth.

**Comment by lccezinha** [comment]
Acho 3 meses muito, quase sempre a vaga já foi preenchida. Poderia ser algo:

- Job sem cadastro 1 semana
- Job com registro 1 mês

**Comment by matheusml** [comment]
O problema de deixar tempos curtos é o site ficar vazio.
O ideal é termos um número considerável de vagas, isso estimula
tanto pra quem quer postar novas vagas quanto pros devs que estão a procura.

**Comment by lccezinha** [comment]
E se tivesse algo do tipo "Vagas em destaque" que seriam as vagas de pessoas que se registraram no site, ela poderia ficar mais acima na busca ou quem sabe numa guia separada (embora não ache muito bom pro site não fica muito cheio de coisas) e para aqueles que não se cadastraram a vaga vem mais abaixo.

**Comment by Brunozrk** [comment]
O que acham de fazer o seguinte, só para organizar:

  * 1º - Criar o admin para facilitar a exclusão dos jobs fakes (abrir issue para isso);
  * 2º - Acho que a ideia de dar vantagens para quem é autenticado é uma boa. Só precisamos decidir quais vantagens e tal, uma nova issue para isso?

Assim podemos fechar essa e separar as discussões, o que acham?

**Comment by matheusml** [comment]
@Brunozrk +1

**Comment by matheusml** [comment]
@Brunozrk Estou fechando essa. Pode criar as duas?

**Comment by Brunozrk** [comment]
Admin - https://github.com/ruby-jobs/ruby-jobs/issues/6
Login - https://github.com/ruby-jobs/ruby-jobs/issues/7
