### ISSUE TITLE
Alterar posição/estilo de campos

### ISSUE THREAD

**Issue by matheusml** [ruby-jobs/ruby-jobs#30]
Os campos salário/tipo de contratação aparecem no final da vaga e sem nenhum destaque.
Ambos deveriam aparecer em cima e com alguma forma de destacação.

**Comment by lucasnogueira** [comment]
Acho que rolou algum problema com os `assets` porque o css não rolou no merge. Precompile talvez?

**Comment by matheusml** [comment]
@lucasnogueira Done.
