### ISSUE TITLE
Remover Vaga Já Preenchida

### ISSUE THREAD

**Issue by thiagoramos23** [ruby-jobs/ruby-jobs#39]
Galera, recentemente criei uma vaga no RubyJobs e a vaga já foi preenchida. Seria legal ter uma possibilidade de remover a vaga. 

Andei pensando e nem precisaria implementar uma autenticação no sistema. Simplesmente ao clicar em remover a vaga seria enviado um email para o criador da vaga com um botão para confirmar a exclusão da vaga. 

O que acham?

**Comment by esasse** [comment]
Eu concordo com a solução proposta. Simples e resolve o problema.

**Comment by Brunozrk** [comment]
Isso pode encher sua caixa de e-mail se pessoas mal intencionadas ficarem clicando no botão :disappointed:

**Comment by esasse** [comment]
Putz, é verdade!

**Comment by Brunozrk** [comment]
O painel administrativo resolveria bem esse problema rsrs

**Comment by thiagoramos23** [comment]
É verdade. É uma pena que existam pessoas mal intencionadas. 
Como você pensa que poderia ser @Brunozrk ?

Eu posso fazer o painel.

**Comment by esasse** [comment]
A url tokenizada também. Hehe

**Comment by Brunozrk** [comment]
pois é :cry: 

Entao @thiagoramos23, discutimos sobre ter que se autenticar para inserir jobs aqui https://github.com/ruby-jobs/ruby-jobs/issues/7

Com essa funcionalidade, para cada job podemos deixar uma flag(ativo|inativo), assim você no seu painel adm pode ativar a inativar a hora que quiser. Ou excluir o job mesmo...

**Comment by thiagoramos23** [comment]
Eu tava olhando essa issue #7. Só pra confirmar porque ficou meio confuso a discussão lá. 
As funcionalidades seriam: 
1. Criar autenticação
2. Criar o painel com informações sobre os jobs para poder editar, ativar/desativar e excluir.

certo?

**Comment by Brunozrk** [comment]
Isso!

É que la estavamos discutindo também o que poderiamos fazer para incentivar a galera a se cadastrar no sistema.

A ideia inicial é nao impedir que empresas deixem de inserir jobs sem se autenticar, porém empresas autenticadas teriam algumas vantagens.

Esse cadastro também poderia ser feita através de outras redes (facebook, linkedin, etc)

**Comment by matheusml** [comment]
Lembrando que por enquanto não temos nenhuma forma de monetização, então enviar e-mails, podem acarretar gastos.

**Comment by lccezinha** [comment]
HOJE a melhor solução acho que seria excluir diretamente do DB.. apenas de feio funcionaria. Por que já tivemos muitas conversas sobre o que fazer sobre essa situação e nunca chegamos a nenhuma conclusão :/

**Comment by thiagoramos23** [comment]
Galera, não sei se teria que criar um outro tópico, mas andei vendo que o projeto também tem angulares. Como preferem criar a parte de autenticação e as telas de admin, com angular?
Pensei em fazer a autenticação com devise à princípio e, como não tenho experiencia(embora conheça algo) com AngularJS, fazer o admin com rails e erb normal. 

O que acham?

**Comment by lccezinha** [comment]
Com autenticação tu quer dizer o que ?

Todo usuário ter que se registrar no sistema para postar um Job ?

Ou apenas criar um interface admin para que um usuário admin do projeto (no caso @matheusml ou @Brunozrk) possam apagar determinado job já preenchido ?

**Comment by thiagoramos23** [comment]
O que eu é quero dizer é criar um processo de sign_in / sign_up e as telas de admin com listagem das vagas e possibilidade de edição e exclusão.

Quero saber se é tranquilo usar Devise à princípio.

**Comment by lccezinha** [comment]
Essa parada de login ou não nós já discutimos aqui e nunca chegamos a conclusão nenhuma sobre isso.. ou chegamos @brunozrk @matheusml  ?

Eu voto numa opção assim: criar um admin (rails_admin ou active_admin) e quem é o dono do projeto @matheusml tem acesso e ele poder excluir e editar os jobs necessários... pq eu acho que criar um login sempre que um user precisar postar um job irá criar uma barreira desnecessária no momento.

**Comment by matheusml** [comment]
@lccezinha +1

Estamos debatendo sempre a questão do admin para criação de novos Jobs mas nunca chegamos em nada bom o suficiente pra ser implementado, visto que a maioria das soluções cria essa barreira a mais que pode 'espantar' alguns usuários.

**Comment by lucasnogueira** [comment]
Achei legal a ideia.

Unindo isso com a ideia de cobrar para postar uma vaga, poderíamos começar
a limitar de fato o número de dias que o job fica no site (20 por exemplo).
Caso a empresa resolva pagar ela ganharia um login, podendo assim editar e
remover livremente seus jobs. Além disso poderia ser criada uma área de
destaque, colocando esses jobs na frente dos de não pagantes e deixando
explícito que são patrocinados, explicando a ideia por trás disso (ajudar
caridade, financiar eventos da comunidade, etc).
Em 11/04/2015 22:33, "Matheus Lima" <notifications@github.com> escreveu:

**Comment by lccezinha** [comment]
Não sei qual o volume de acessos/cadastros do site, mas acho que AINDA não é hora pra pensar nesse tipo de situação, ou seja, acho um pouco cedo para começar a fazermos cobranças.

Também tive essa idéia do destaque para jobs pagos, porém como disse acima, acho cedo pra começar a cobrar por postagem de job. :/

**Comment by matheusml** [comment]
Estamos em média com 2.2k/mês de acessos.

**Comment by brunozrk** [comment]
Essa questão do admin ta assim:

Tudo certo e nada resolvido!

haha, enfim, o que vcs acham de fazermos uma pequena pesquisa com o pessoal que ja postou vaga para sabermos a opnião deles, afinal, essas discussões afetam eles diretamente.

Na pesquisa agente coloca todas as opcões que foram dadas aqui: login para postar vaga, um admin pra gente mesmo controlar mais facil, token por job, etc.

Acham válido?

**Comment by esasse** [comment]
Eu não faria essa pesquisa com usuários. Acho que seria de muito pouco interesse para eles e não seria simples explicar as opções. Acho que isso tem que ser decidido entre as pessoas que colaboram com o código do site mesmo.

De qualquer forma, eu entendi que isso já está definido na #7. Vai ser login do usuário pelo facebook/google/linkedin, etc para ele mesmo gerenciar a vaga.

**Comment by matheusml** [comment]
@esasse +1

**Comment by ThiagoJota** [comment]
Fala galera, chegando agora por aqui.

Uma sugestão era gerar uma "senha" de alteração de status. Para cada job cadastrado o sistema iria gerar e exibir a senha para o usuário.  E na solicitação de alterar o status para "preenchida" o sistema cobraria esta senha.

O que acham?

**Comment by esasse** [comment]
Foi uma das [sugestões](https://github.com/ruby-jobs/ruby-jobs/issues/7#issuecomment-72766351) que eu dei algum tempo atrás.

**Comment by esasse** [comment]
Acho inclusive que deveríamos unificar estas duas issues, pois as discussões estão ficando duplicadas. Essa #39 com a #7.

**Comment by lccezinha** [comment]
@esasse faz sentido unificar, acho que poderia fechar aquela que é mais antiga e deixar essa aberta pra continuar a discussão.

**Comment by thiagoramos23** [comment]
Galera, sem querer parecer chato ou grosseiro. Eu acho que o que deveria ser feito é acabar com discussão e tomar logo uma decisão. Já foram tantas idéias e discussões que tem gente que nem lembra mais a idéia que deu ou nem lembra mais o que quase todo mundo está concordando. Enfim, é chegar em um finalmente.

**Comment by esasse** [comment]
Concordo. :+1:

**Comment by matheusml** [comment]
@thiagoramos23 se formos ter que tomar uma decisão rápida, então seria: deixar exatamente como está e não mudar. Basicamente porque nenhuma das soluções apresentadas são boas o suficiente. Mas um caminho a ser tomado poderia ser um login por FB para que cada um faça administração dos jobs cadastrados.

**Comment by ThiagoJota** [comment]
Podemos também solicitar o e-mail na hora do cadastro do job.

E com o mesmo e-mail a pessoa poderia atualizar o job.

Considerando que este e-mail não seria exibido na opção da vaga.

**Comment by thiagoramos23** [comment]
@matheusml tranquilo.

**Comment by esasse** [comment]
@matheusml qual o procedimento certo hoje para remover uma vaga? Perguntando aqui pois esse é o assunto da issue e eu também preciso remover uma vaga que publiquei.

**Comment by matheusml** [comment]
Hoje eu recebo um e-mail de quem postou, e removo em até 24h.
Tá longe de ser o ideal, mas infelizmente não vi melhoria nas propostas apresentadas.

**Comment by lucassaldanha** [comment]
@matheusml Pelo que entendi você está apagando as vagas manualmente correto? O que acha de tentar pelo menos automatizar esse processo?

1. Ao criar a vaga o criador recebe um token de identificação (pode ser no *jobs:create:notice* mesmo ou por email);
2. Ao receber um email com esse token (é possível ter um job para monitorar uma inbox) e o assunto "Apagar" (por exemplo), o sistema pode buscar a vaga associada a este token e apagá-la;
3. O sistema envia ao email associado a vaga uma notificação de remoção de vaga (ou não caso queira evitar custos com envio de email)

É simples mas pelo menos não precisaria ser feito de forma manual. :)

**Comment by esasse** [comment]
Mais simples que isso seria usar o token para poder editar/apagar a vaga, não?

**Comment by lucassaldanha** [comment]
> Mais simples que isso seria usar o token para poder editar/apagar a vaga, não?

@esasse Você diz para que o próprio usuário possa editar/apagar a vaga?

Concordo que seria mais completo (não sei se necessariamente mais simples), mas envolveria ter que fazer modificações de interface e a criação de uma espécie de "área administrativa", que pelo que acompanhei da discussão é desejada mas ainda não será feita.

Como você pensou em utilizar esse token? Qual seria o fluxo do usuário para apagar/editar a vaga?

**Comment by esasse** [comment]
Já expliquei umas três vezes minha ideia em outras issues. Acho melhor não repetir tudo aqui porque o pessoal não vai gostar muito. 😁

**Comment by lucianosousa** [comment]
Galera, acho que essa issue deveria ser reaberta. Ou então reabrir as issues relacionadas.

A proposta de criar um dashboard em algum momento morreu. Sugiro repensar a idéia de como remover um anúncio
