### ISSUE TITLE
Codeclimate

### ISSUE THREAD

**Issue by brunozrk** [ruby-jobs/ruby-jobs#41]
Galera, coloquei nosso repo no codeclimate, e a nota não ta nada boa! haha

Mas isso é pelos assets pre compilados que temos no repo, o ideal é remover e o heroku executar o precompile no momento do deploy.

Segue o link no code climate:

https://codeclimate.com/github/ruby-jobs/ruby-jobs

**Comment by esasse** [comment]
Ótimo! Legal agora é:

- Ativar a integração com pull requests, assim ele analisa automaticamente cada PR.
- Ativar code coverage
- Colocar as badges no readme.

**Comment by brunozrk** [comment]
:+1:

**Comment by brunozrk** [comment]
@esasse, configurei [aqui] (https://github.com/ruby-jobs/ruby-jobs/pull/44)  para ativar o code coverage.

Com relação aos prs, parece que já esta integrado!

**Comment by brunozrk** [comment]
Ops, o codeclimate não está analisando os PRs não, rsrs

**Comment by esasse** [comment]
Se não me engano, precisa ativar nas configurações do projeto.
