### ISSUE TITLE
Sugestão: Adicionar um collection_select no campo de localização

### ISSUE THREAD

**Issue by marcelobarreto** [ruby-jobs/ruby-jobs#43]
Fala ai pessoal, ninguém me conhece aqui ainda, quer dizer, quase ninguém né @brunozrk ?
To começando no ruby on rails agora e estou treinando e estudando bastante, e vou tentar ajudar no que eu puder nesse projeto.

Minha primeira sugestão seria colocar um collection_select no campo de localização, o que vocês acham? Na minha opinião, ficaria mais padrão.

**Comment by brunozrk** [comment]
Marcelo, como seria, uma combo pra estado e outra pra cidade?

**Comment by marcelobarreto** [comment]
Que tal colocarmos só a cidade e de acordo com a cidade, o estado já aparecer preenchido...
Se precisarem, tenho como exportar uma tabela de municípios pronta com todas cidades e estados já

**Comment by marcelobarreto** [comment]
E outra coisa @brunozrk , o que acha de colocarmos uma checkbox caso o job seja remoto também?

**Comment by matheusml** [comment]
Lembrando que temos vagas internacionais também, então não podemos nos limitar a uma lista fixa.

**Comment by brunozrk** [comment]
@marcelobarreto, para trampos remoto ja temos no campo `Qual é a modalidade de trabalho?`

Bem lembrado @matheusml...

**Comment by marcelobarreto** [comment]
Beleza então galera, posso fechar esse issue?

**Comment by brunozrk** [comment]
Uma solução seria colocar um autocomplete ao invés de uma combo, assim padroniza o que tem, mas não impede de colocar o que não tem, o que acham?

**Comment by matheusml** [comment]
Aí sim seria interessante.

**Comment by marcelobarreto** [comment]
achei legal @brunozrk

**Comment by lucasfurtado** [comment]
Bem melhor com autocomplete.

**Comment by lccezinha** [comment]
autocomplete :+1:
