### ISSUE TITLE
Exibir a descrição da vaga no feed

### ISSUE THREAD

**Issue by gabrielsme** [ruby-jobs/ruby-jobs#46]

**Comment by esasse** [comment]
Parece uma boa ideia. :+1:

**Comment by esasse** [comment]
Já não tem? https://github.com/ruby-jobs/ruby-jobs/blob/master/app/views/jobs/feed.atom.builder#L11

**Comment by esasse** [comment]
No XML até tem, mas no leitor não aparece mesmo:

![screen shot 2015-05-05 at 23 35 24](https://cloud.githubusercontent.com/assets/148989/7486704/81e9bf76-f37f-11e4-8bb7-886efb182f0e.png)

![screen shot 2015-05-05 at 23 38 41](https://cloud.githubusercontent.com/assets/148989/7486731/e8e70a3a-f37f-11e4-85b4-620b6b8d1bb9.png)

E o feed não passa no validador: http://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Fwww.rubyjobs.me%2Ffeed

**Comment by esasse** [comment]
Deixem comigo, vou tentar resolver isso.
