### ISSUE TITLE
Problema na tela de pesquisa

### ISSUE THREAD

**Issue by thiagoaugusto** [ruby-jobs/ruby-jobs#54]
Galera, a pesquisa está retornando apenas os registros que já aparecem na tela.
Se você pesquisar por alguma vaga que não esteja aparecendo na tela, a pesquisa não retorna nada.

**Comment by matheusml** [comment]
Provavelmente foi usado o filter simples que vem built-in do AngularJS.
Uma solução seria fazer um novo request.

**Comment by jmscarpa** [comment]
vou pegar isso para resolver ok?

**Comment by matheusml** [comment]
@jmscarpa fechado!
