### ISSUE TITLE
Criar o admin para facilitar a exclusão dos jobs fakes

### ISSUE THREAD

**Issue by Brunozrk** [ruby-jobs/ruby-jobs#6]
Criar parte administrativa do site.

Funcionalidades
  * Listar jobs
  * Excluir job
  * Editar job? (Derrepente corrigir algum erro, o que acham dessa func?)

Acredito que para esse momento o [activeadmin](https://github.com/activeadmin/activeadmin) resolva isso de forma rápida e fácil.

**Comment by matheusml** [comment]
Editar job é uma boa sim, diversas vezes recebi um e-mail com a requisição.

**Comment by lccezinha** [comment]
activeadmin +1.. não vai dar dor de cabeça e vai ser simples de usar.

**Comment by lccezinha** [comment]
eae vai rolar fazer isso usando activeadmin ou alguem tem outra idéia?

**Comment by Brunozrk** [comment]
Acho que pode ser no activeadmin!

**Comment by lccezinha** [comment]
e o activeadmin rola de boa mesmo sem ter tabela de usuários p/ ele fazer o login ? Nunca usei ele sem isso então não sei como ele se comporta.

**Comment by Brunozrk** [comment]
Acredito que vai ter que criar a tabela, rsrs.

A propria instalação dele ja faz isso, não é?

**Comment by matheusml** [comment]
Estou repensando nessa tarefa.
Temos duas motivações para fazê-la:
1) Remoção de Jobs fake que deveriam ser removidos o mais rápido possível.
2) Manage de Jobs por parte de quem criou.

O ponto 2 não faz sentido, porque iremos fazer pelo esquema de login com FB/LinkedIn,
então só resta o ponto 1.

O ponto 1 é extramemente raro, só consigo me lembrar de dois jobs fakes que foram criados até o momento, sendo que eu levo menos de 1 dia pra ir no banco e removê-lo, então fica a pergunta: vale a pena continuar cogitando essa tarefa?

**Comment by lccezinha** [comment]
acho que se for pelo caso de remover fakes não vale a pena, pois é bem simples ir pelo console da app e remover por lá não ?

**Comment by matheusml** [comment]
Exato. Mas é um processo manual, que pode levar mais tempo do que deveria.

**Comment by Brunozrk** [comment]
De fato não tem acontecido muito. Acho que podemos fechar essa issue
