### ISSUE TITLE
Ativar integração do Code Climate nos PRs

### ISSUE THREAD

**Issue by esasse** [ruby-jobs/ruby-jobs#62]
Acho que este artigo deve ajudar: http://docs.codeclimate.com/article/213-github-pull-request-integration

**Comment by matheusml** [comment]
+1

**Comment by lccezinha** [comment]
:+1:

**Comment by esasse** [comment]
Quem tem acesso ao projeto no Code Climate? Eu posso fazer isso se me derem acesso. Tenho vários outros projetos lá, sei como funciona.

**Comment by matheusml** [comment]
Feito!
