### ISSUE TITLE
Adicionar informações completas no feed

### ISSUE THREAD

**Issue by esasse** [ruby-jobs/ruby-jobs#63]
Hoje o feed é meio pobre. Um job aparece assim no feed:

![image](https://cloud.githubusercontent.com/assets/148989/8432660/c4b77bae-1f17-11e5-8f4e-d5884885ec06.png)

E assim na web:

![image](https://cloud.githubusercontent.com/assets/148989/8432679/da23c29a-1f17-11e5-8faf-e38800bb2b46.png)

Ideal seria já trazer tudo no feed, inclusive com o link para o interessado entrar em contato sobre a vaga e participar do processo de seleção.

**Comment by rodrigomonteirof** [comment]
Posso pegar essa tarefa para dar uma olhada?

**Comment by rodrigomonteirof** [comment]
No arquivo "app/views/jobs/feed.atom.builder" está sendo adicionado somente no content um "item.description, type: html", o item.skills não esta sendo adicionado...

Nesse caso é melhor adicionar um "type: skills" ou apenda dentro do "type: html" mesmo?

**Comment by esasse** [comment]
Não sei, precisa testar.

**Comment by rodrigomonteirof** [comment]
Dois dois jeitos funcionam, muda a organização... achei melhor deixar a marcação somente como skills mesmo....

Criei um merge request, se alguem puder dar uma olhada!!! 

Meu primeiro merge no rubyjobs e em opensource :)

**Comment by esasse** [comment]
Que legal @rodrigomonteirof, seja bem-vindo! :smile:
