### ISSUE TITLE
Colocar sqlite3 no droup test/develepment

### ISSUE THREAD

**Issue by rodrigomonteirof** [ruby-jobs/ruby-jobs#66]
Pessoal,

Estou caindo agora de paraquedas, clonei o projeto recentemente e me veio essa dúvida: 

O que vocês acham de colocar a gem sqlite3 no grupo test/development para faciltar o ambiente necessario para contribuir?

Desculpe se o assunto ja foi debatido, procurei e não achei nada a respeito.

**Comment by matheusml** [comment]
Ele já foi assim na verdade,
mas a gente resolveu remover e usar o pg pra tentar ficar com todos ambientes semelhantes.
Mas podemos reabrir a questão.

O que acham? @brunozrk @esasse @jmscarpa @lccezinha

**Comment by esasse** [comment]
Na minha opinião, quanto mais parecido os ambientes melhor, então eu voto por usar pg em desenvolvimento e testes também.

Vejam: http://12factor.net/dev-prod-parity

Nos meus projetos eu inclusive costumo usar `Rails.env == "production"` mesmo em desenvolvimento.

**Comment by lccezinha** [comment]
Voto por manter o ambiente similar entre os dois, +1 pra usar/manter PG em dev/test.

**Comment by jmscarpa** [comment]
+1 pg

2015-07-01 14:54 GMT-03:00 Luiz Cezer <notifications@github.com>:

> Voto por manter o ambiente similar entre os dois, +1 pra usar/manter PG em
> dev/test.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ruby-jobs/ruby-jobs/issues/66#issuecomment-117766447>.
>



-- 
Atenciosamente,

*João Mateus Scarpa*
http://jmscarpa.com.br
(12) 99222-3938

**Comment by brunozrk** [comment]
atrasado, mas pg +1 rsrs
