### ISSUE TITLE
Eriquecer as informações na listagem dos jobs

### ISSUE THREAD

**Issue by rodrigomonteirof** [ruby-jobs/ruby-jobs#68]
Galera,

Só eu que me incomodo em ter que entrar em uma vaga para só depois descobrir que é de "Contratação: PJ e Salário: R$3.000 - R$6.000"?

Sera que não compensa colocar essas informaçẽos já na listagem dos jobs?

Eu gostaria que igual exibe a faixa de "Remoto/Presencial" já mostraria o tipo de contratação e a faixa saliaral...

**Comment by matheusml** [comment]
Acho dificil conseguir encaixar mais informações na listagem inicial sem que estrague um pouco do design. Mas se você apresentar uma solução boa, não vejo porque não aceitar.

**Comment by rodrigomonteirof** [comment]
Não sou bom de design, só trabalho com backend... mas imaginei que para não estragar o design poderiam criar uns selos ou iconizinhos para colocar no cantinho... 

algo tipo assim:
1 moedinha: "Abaixo de R$3.000"
2 moedinhas: "R$3.000 - R$6.000" 
3 moedinhas: "R$6.000 - R$9.000"
4 moedinhas ou um saquinho de dinheiro?: "Acima de R$9.000"

Algo nessa linha, ai teriamos selos para CLT/PJ e uns para Presente/Remoto.

E para explicar o que significa poderiamos deixar no ALT do IMG... ai se alguem parar o mouse em cima aprende o que o icone significa...

**Comment by rodrigomonteirof** [comment]
Ou até usando o próprio emoji mesmo, para não ter o trabalho de desenhar os icones:

http://www.emoji-cheat-sheet.com/

Abaixo de R$3.000: baby
R$3.000 - R$6.000: boy
R$6.000 - R$9.000: man
Acima de R$9.000: older_man

**Comment by matheusml** [comment]
É uma boa ideia mesmo.
Vamos ficar no aguardo de alguém mais UX/UI...

**Comment by brunozrk** [comment]
Boa, tbm acho válido :smile:

**Comment by rodrigomonteirof** [comment]
![screenshot from 2015-07-17 19 35 37](https://cloud.githubusercontent.com/assets/3018798/8758488/1887d66a-2cbb-11e5-85c9-fc6ef3d0dfc5.png)

Seria algo mais ou menos assim, faltando algum icone para CLT/PJ... então só de olhar a short description da para saber os tudo sobre a vaga

**Comment by esasse** [comment]
Eu não gosto tanto da ideia de ícones. Ícones são mais úteis quando você sabe exatamente o que cada um significa sem ter que pensar ou passar o mouse em cima. Lembrando que no celular ou tablet, você não tem o recurso "passar por cima".

Acho que não seria muito difícil encaixar essas informações como texto mesmo na listagem. Depois posso fazer um mockup aqui e enviar.

**Comment by esasse** [comment]
Para ilustrar o que eu comentei, acho que ficaria bom algo assim:

![image](https://cloud.githubusercontent.com/assets/148989/8768369/4cff1990-2e54-11e5-8e82-7ba0aec5d34f.png)

**Comment by matheusml** [comment]
@esasse +1

**Comment by rodrigomonteirof** [comment]
Acho os iconizinhos mais bem humorado...rsrs, mas o jeito do @esasse tambem resolve o problema!

**Comment by rodrigomonteirof** [comment]
Uma outra coisa que reparei é que tem código duplicado na listagem do index e na do /jobs... geram o mesmo HTML, o index usa um @jobs.each e jobs usa um json com angular...

**Comment by rodrigomonteirof** [comment]
Conversei com um amigo meu e ele vai fazer essa alteração... Depois que ele terminar, gostaria de extrair o código repetido em uma partial e deixar do mesmo jeito a listagem do "index" e do "/jobs"

**Comment by orfenes** [comment]
Opa galera o amigo que é front sou eu vou contribuir e fazer essa alteração

**Comment by matheusml** [comment]
Beleza @rodrigomonteirof e @orfenes 
Mas tentem criar uma issue específica pra isso pra não misturarmos as coisas.

**Comment by esasse** [comment]
+1 para extrair a listagem para um partial e remover código duplicado. O bug que eu corrigi ontem na formatação das datas provavelmente só existiu por esse motivo.

**Comment by mguilarducci** [comment]
A ideia dos ícones é bem bacana, mas vendo o exemplo eu achei confuso. Acho que ficaria difícil de entender :disappointed: 

@esasse :+1:
