### ISSUE TITLE
Autenticação para inserir job

### ISSUE THREAD

**Issue by brunozrk** [ruby-jobs/ruby-jobs#7]
Conforme conversado (https://github.com/ruby-jobs/ruby-jobs/issues/3):

**Para cadastrar um job não é obrigatório o login.**
Porém, para incentivar a galera a se cadastrar para postar o job, devemos oferecer algumas vantagens.

### Usuário autenticado:
* Edição do job após ser criado.
* Exclusão do job.
* Job fica visível por *X* dias.
* ...?

### Usuário não autenticado:
* Job fica visível por *Y* dias.

Apenas algumas sugestões, conforme formos discutindo eu atualizo aqui!

**Comment by matheusml** [comment]
A princípio eu faria 1 semana pra não logados e 3 meses pra logados.

**Comment by lccezinha** [comment]
3 meses é bastante tempo .. pode ser que a vaga já tenha sido preenchida.

**Comment by esasse** [comment]
E porque precisa incentivar o cadastro?

Eu ainda não tenho certeza que um cadastro é necessário. Algumas alternativas mais simples:
- Uma URL "secreta" (com um token) por exemplo, que o usuário recebe por e-mail ao cadastrar a vaga e usando essa URL ele consegue editar a vaga.
- Uma senha por vaga, que ele também recebe por e-mail e precisa dela para confirmar uma alteração na vaga.

**Comment by Brunozrk** [comment]
@esasse, vc como empresa, nao gostaria de ter controle sobre seu jobs? Podendo editar, excluir, ver numero de visualizações ou qlq outra coisa?

Se vamos dar opcao de edição e exclusão, um cadastro é essencial, suas alternativas funcionam, mas acho que não fica legal ficar gerando token ou senha por job.

Essa é minha opinião rsrs

O que o restante acha?

**Comment by esasse** [comment]
Acho que ninguém precisa de nada muito elaborado não nesta área não. O padrão em qualquer site é criar login, usuário, senha, etc. Mas sempre podemos inovar e criar algo bem mais simples que resolva o problema.

Porque você acha que os tokens não seriam legais?

**Comment by Brunozrk** [comment]
Acho que fica ruim para o usuário ficar guardando a url pra acessar seu job.

Se ele cadastrar 3 jobs, terá 3 urls. Assim ele tem que ficar gerenciando essas urls fora do site (no email, bookmark, etc).

**Comment by esasse** [comment]
Minha ideia é que ele receba um e-mail com a confirmação da vaga publicada e a URL "secreta" (ou a senha) para manutenção da vaga. Ele só precisaria guardar o e-mail, e hoje em dia todo mundo já gerencia e-mail.

Outra coisa legal é que também podemos depois incluir uma opção **"Está vaga é sua? Receba por e-mail as instruções para edição"**, e ao clicar, reenviamos para o e-mail cadastrado na vaga as instruções. Isso resolve o problema dele perder o e-mail.

Outra facilidade menos importante mas que pode ser interessante para alguns usuários é a possibilidade de compartilhar a manutenção da vaga. Se eu criei a vaga e recebi o e-mail, posso encaminhar para outras pessoas da minha equipe envolvidas no processo de seleção e elas conseguiriam também editar, excluir, etc. Sem ter que compartilhar login e senha e ainda permitindo compartilhar só as vagas necessárias e também com pessoas diferentes se for o caso.

**Comment by matheusml** [comment]
@esasse apesar de eu ter gostado da ideia, eu acho que se pensar como o usuário, é muito mais dificil ficar fazendo manage dos Jobs através de tokens diferentes para cada um. Acho bem mais fácil, de novo, pensando como um usuário, ele ter um login com facebook/LinkedIn e poder alterar todos seus Jobs.

**Comment by esasse** [comment]
Tudo bem, sem problemas! Apesar de eu achar que a minha solução resolve bem os problemas e é muito mais simples de codificar, eu concordo que ficará muito legal ter o login via facebook/linkedin/google/etc e ter acesso a todos seus jobs, estatísticas, etc. :+1:

**Comment by keernel** [comment]
Ao meu ver, o problema das URLs tokenizadas, seria a segurança das informações sobre a vaga.
Muito fácil de alterar caso algum terceiro tenha acesso a este link.

E comparado com a opção de ter um painel de controle pra controlar os jobs, fica fácil decidir.

**Comment by esasse** [comment]
Não vejo como um problema, pois um anúncio de vaga não é exatamente algo muito crítico. Ainda prefiro a solução mais simples.

**Comment by keernel** [comment]
Isso é relativo. Não é crítico a ponto de causar dano à alguém, mas seria bem chato se algum fanfarrão ficasse alterando os anúncios dos outros. E a partir daí teríamos sim um ou vários problemas, onde a solução seria obviamente a nossa outra opção de implementação. 
Ou seja, mais seguro e eficiente seguir com a opção de painel de controle. Que não precisa ser complexa, não precisa ter funcionalidades como estatísticas e etc neste momento, apenas permitir que o usuário possa controlar seus anúncios. Sabemos que isso não é nada difícil de implementar.

**Comment by keernel** [comment]
Outra coisa, acredito que este tópico já havia sido discutido aqui #3 e foi votado para o Painel certo?

**Comment by esasse** [comment]
No fim tudo é meio relativo. ;)

Mas sim, já foi votado pelo painel e pra mim essa discussão também [já tinha sido concluída](https://github.com/ruby-jobs/ruby-jobs/issues/7#issuecomment-73059164).  Como você a retomou, vim aqui defender meu ponto.

Aguardaremos uma boa alma criar o painel. :+1:
