### ISSUE TITLE
Botões de compartilhar (LinkedIn e Twitter)

### ISSUE THREAD

**Issue by matheusml** [ruby-jobs/ruby-jobs#72]
Os botões continuam funcionando, mas as labels sumiram:

http://www.rubyjobs.me/jobs/178-senior-ruby-developer-berlin-or-remote

**Comment by esasse** [comment]
Não sei se entendi bem a qual label você está se referindo, mas eu lembro de ter mexido nisso por pedido seu mesmo. Veja #49.

**Comment by matheusml** [comment]
Esquece.. provavelmente era cache..
