### ISSUE TITLE
Internacionalização

### ISSUE THREAD

**Issue by matheusml** [ruby-jobs/ruby-jobs#74]
Discussão:

Tenho visto algumas vagas internacionais, mesmo com o site sendo 100% em português, então me veio a questão de traduzir o site inteiramente para o inglês. Com isso podemos escalar o RubyJobs para um patamar muito acima do que já temos hoje.

**Comment by esasse** [comment]
Acho que faz sentido. O site já tem um nome "internacionalizado", não vejo porque não traduzir por completo. :+1:
