### ISSUE TITLE
Internacionalizar a aplicação

### ISSUE THREAD

**Issue by matheusml** [ruby-jobs/ruby-jobs#75]
Conforme debatido no #74 devemos substituir tudo que está em português no site e traduzir para o inglês, visando um maior público e maior uso da aplicação.

**Comment by lucasnogueira** [comment]
Mas as vagas continuarão em português correto?

**Comment by matheusml** [comment]
Sim, nada será feito no banco de dados. Quem quiser postar vaga em português, está totalmente livre pra isso.

**Comment by matheusml** [comment]
PS.: Já tô pegando essa...

**Comment by rafa-so** [comment]
@matheusml boa tarde,
sou novo em rails, e gostaria de pegar essa parte também (até por que atualmente tenho estudado esta parte). Como seria este esquema? Como dividir esta issue?

**Comment by matheusml** [comment]
@rafa-so o que você tá pensando em fazer?

**Comment by rafa-so** [comment]
@matheusml pegar algumas telas para internacinalizar, colocando as chaves criadas tanto no arquivo de reponsável pelo inglês, quanto no de português.... Acho que é isso.... Se você tiver alguma sugestão....

**Comment by matheusml** [comment]
Que tal fazer o seguinte então: eu traduzo o site inteiro para inglês, hardcode mesmo, sem arquivo para inglês/português, e depois você faz esse incremento.

**Comment by rafa-so** [comment]
@matheusml beleza então, por mim está tranquilo. Enquanto isso então vou dando prosseguimento aos estudos, e aguardo o seu sinal do que eu já posso ir alterando.

**Comment by lccezinha** [comment]
:clap:

**Comment by matheusml** [comment]
@rafa-so me parece que agora só falta criar um ```en``` no ```jobs.yml``` com as traduções e verificar uma ou outra string que ainda tá jogada pela aplicação.

Rola pegar? o/

**Comment by rafa-so** [comment]
show cara, rola sim \o/

2015-10-06 21:54 GMT-03:00 Matheus Lima <notifications@github.com>:

**Comment by matheusml** [comment]
Galera, o @rafa-so não vai poder continuar nessa task. Alguém quer pegar?

**Comment by frenangomes** [comment]
Cara, eu gostaria de pegar essa task. Pelo histórico é só criar  a chave en e verificar se tem alguma string jogada certo?

**Comment by matheusml** [comment]
@frenangomes perfeito.

**Comment by douglas-queiroz** [comment]
@matheusml essa issue já foi fechada? Posso ajudar?

**Comment by matheusml** [comment]
Tá em aberto ainda @douglas-queiroz 
Ajuda é muito bem-vinda o/

**Comment by douglas-queiroz** [comment]
=)
Hoje vou dar uma analisada no que o @rafa-so estava fazendo para seguir na mesma linha.

**Comment by rafa-so** [comment]
@douglas, não fiz nada, infelizmente, acho que pode continuar de onde parou
mesmo.... eu pelo menos não fiz nada.

[]s

Em 24 de novembro de 2015 11:12, Douglas Queiroz <notifications@github.com>
escreveu:

**Comment by douglas-queiroz** [comment]
OK @rafa-so, li rápido os comentário, achei q vc já estava fazendo algo.

**Comment by douglas-queiroz** [comment]
@matheusml como vai ser a parametrização do location? Vai haver pt-BR e Inglês ou teremos apenas uma versão em inglês? Estou peguntando isso pq percebi que em um post você falou em criar uma chave en, por isso fiquei em dúvida.

**Comment by matheusml** [comment]
Já existe um arquivo de locale, só que ele está em português. A ideia é mantê-lo e criar um para inglês e deixá-lo como default.

**Comment by douglas-queiroz** [comment]
blz! vlw!

**Comment by douglas-queiroz** [comment]
@matheusml adicionei as traduções do jobs no en e setei o en com default, também alterei algumas strings do jobs helper. #83.

**Comment by douglas-queiroz** [comment]
@matheusml as outras String q estão hardcode, posso substituir ou coloco no en também?

**Comment by matheusml** [comment]
Sim, @douglas-queiroz era exatamente esse ponto que faltava...
