### ISSUE TITLE
Bugsnag

### ISSUE THREAD

**Issue by esasse** [ruby-jobs/ruby-jobs#78]
Tenho usado o [Bugsnag](https://bugsnag.com) nos meus projetos e gosto bastante. Eles permitem [uso gratuito em projetos open source](https://bugsnag.com/blog/bugsnag-loves-open-source). O que acham de ativarmos ele no ruby-jobs?

**Comment by matheusml** [comment]
Existe algum passo-a-passo para a configuração? E mais importante, os reports que são gerados, são pra que todos possam ver ou vão ficar limitados a minha conta de e-mail?

**Comment by esasse** [comment]
Eu posso configurar e mandar o PR. 

Sobre os relatórios não sei se podem ser totalmente públicos, mas tenho certeza que podem ser compartilhados enviando convites para quem contribui com o projeto, o que já acho bem suficiente. 

O que pode ser feito também é configurar ele para criar issues no GitHub automaticamente.

**Comment by brunozrk** [comment]
Legal @esasse!

Não conhecia, acho válido, se criar issue no github ja resolve eu acredito :+1:

**Comment by matheusml** [comment]
+1 então
