### ISSUE TITLE
Criar 404 customizada

### ISSUE THREAD

**Issue by matheusml** [ruby-jobs/ruby-jobs#8]
Em breve iremos deletar jobs após um período de tempo, 
então devemos informar ao usuário, quando ele entrar num link de job não mais existente (o que podemos simplesmente considerar como 404s), que o job foi removido porque havia expirado o tempo.

**Comment by jmscarpa** [comment]
@matheusml  algum motivo para excluir os jobs? Ou só por questão de "Job expirado" ?

**Comment by matheusml** [comment]
@jmscarpa além da questão dos jobs expirados, eu queria ter poucos registros no Banco.

**Comment by matheusml** [comment]
Um bom modelo seria:

**Job expirado :(**
*Botão que leva pra lista de jobs*

**Comment by jmscarpa** [comment]
Vou pensar em alvo legal esse final dr semana e te mando

**Comment by Brunozrk** [comment]
Vai considerar qualquer 404 como job expirado?

**Comment by matheusml** [comment]
A princípio sim, não vejo muito problema.

**Comment by lccezinha** [comment]
Feito no #29 ?
