### ISSUE TITLE
ExampleException in home#example

### ISSUE THREAD

**Issue by esasse** [ruby-jobs/ruby-jobs#80]
## New exception in Example.com

**ExampleException** in **home#example**
Something really bad happened

[View on Bugsnag](http://bugsnag.com/errors/example/events/example)

## Stacktrace

    app/controllers/home_controller.rb:123 - example
    app/controllers/other_controller.rb:12 - broken
    lib/important/magic.rb:4 - load_something

[View full stacktrace](http://bugsnag.com/errors/example/events/example)

**Comment by esasse** [comment]
Teste criado pelo Bugsnag. Como eu usei um token meu, ele cria em meu nome. Você pode colocar um token seu neste endereço @matheusml: https://bugsnag.com/ruby-jobs/ruby-jobs/issue_tracker/edit

**Comment by matheusml** [comment]
Ele vai criar issues aqui automaticamente nesse modelo acima?

**Comment by esasse** [comment]
isso.

**Comment by matheusml** [comment]
Não gostei muito. Eu tava imaginando algo no tipo do RayGun, para que a gente pudesse somente visualizar os erros 500 em prod, por exemplo. Com esses bugs automáticos aqui, inclusive em ambiente de dev, é bem possível que todo o histórico aqui vire uma confusão e a gente se perca facilmente.

**Comment by esasse** [comment]
Não precisa ativar essa integração com o GitHub, eu mesmo não uso ela em meus projetos. Como eu entendi que você queria algo bem público, essa é a melhor opção. Mas pode deixar tudo no Bugsnag apenas e consultar lá quando quiser. Inclusive você pode configurar para só receber um resumo semanal dos problemas por exemplo.

**Comment by matheusml** [comment]
Seria o ideal. Quando eu falei de algo público, seria um link para que todos pudessem consultar, por exemplo.

**Comment by esasse** [comment]
Blz, eu removi a integração. Ele não vai mais criar issues.
