### ISSUE TITLE
Permitir o uso de "+" no campo de e-mail para contato

### ISSUE THREAD

**Issue by pauloschilling** [ruby-jobs/ruby-jobs#81]
Hoje se tentamos preencher um e-mail para contato no formato alguma+coisa@example.com ele fica como inválido, impossibilitando usar o recurso de alias do Gmail e Google Apps.

Como por aqui temos um email de "carreiras@example.com", ao fazer anúncios usamos sempre um alias para cada vaga, exemplos:

- carreiras+rails@example.com
- carreiras+devops@example.com

Isso nos possibilita criar filtros internos para direcionar os emails para quem está cuidando da vaga, e ao mesmo tempo centralizar tudo em uma mesma conta, porém o RubyJobs acusa como e-mail inválido.

**Comment by matheusml** [comment]
+1

**Comment by esasse** [comment]
:+1:

**Comment by lccezinha** [comment]
Feito no #82

**Comment by lccezinha** [comment]
close @brunozrk @matheusml ?!
