### ISSUE TITLE
Verificação anti-bot

### ISSUE THREAD

**Issue by matheusml** [ruby-jobs/ruby-jobs#87]
Com os recentes, e constantes, ataques por bots criando vagas falsas, pensei numa verificação obrigatória no form de criação de um job.

A ideia seria um campo required no final do form, como um input que verifica o resultado de uma soma simples, ou talvez um reCaptcha. Qualquer uma, desde que faça a verificação de que é um ser humano cadastrando o job.

**Comment by esasse** [comment]
Voto pelo reCaptcha, acho bem mais amigável do que uma soma e outros captchas.

**Comment by matheusml** [comment]
OBS: Eu comentei temporariamente o ```Jobs#Create```. Os ataques estão sendo feitos de minuto a minuto, então enquanto não houver uma solução com o reCAPTCHA o mais seguro é simplesmente bloquear temporariamente a criação de jobs.

**Comment by lccezinha** [comment]
reCAPTCHA +1

**Comment by fabianoarruda** [comment]
Olá pessoal. Como estava com um tempinho livre esse fim de semana, resolvi implementar a solução. acabei de fazer o pull request #88

**Comment by matheusml** [comment]
Obrigado @fabianoarruda !

Basta então criar as chaves e adicionar as duas no ambiente?

**Comment by fabianoarruda** [comment]
Exatamente! As chaves podem ser geradas [aqui](https://www.google.com/recaptcha/admin#list)

depois é só criar as duas variáveis de ambiente:
RECAPTCHA_PUBLIC_KEY
RECAPTCHA_PRIVATE_KEY

**Comment by esasse** [comment]
Acho uma boa colocar as instruções de deploy no readme do projeto.

**Comment by fabianoarruda** [comment]
Bem lembrado @esasse. O site está armazenado em qual serviço? Heroku?

Posso colocar as instruções no Readme, tanto pra rodar local como pra deploy.

**Comment by matheusml** [comment]
@fabianoarruda heroku

Só falta isso mesmo cara. Obrigado!

**Comment by fabianoarruda** [comment]
Atualizei o Readme. Olha lá se tá bom assim.
