### ISSUE TITLE
Layout mobile quebrando

### ISSUE THREAD

**Issue by fabianoarruda** [ruby-jobs/ruby-jobs#90]
Notei que quando acesso o site pelo iPhone o layout tá estourando. Não sei se isto tá acontecendo com outros modelos, só pude testar no meu que é o iPhone 5S. Vejam a screenshot:

![2016-03-29 19 00 12](https://cloud.githubusercontent.com/assets/5299669/14125309/ecaae7c2-f5e0-11e5-9963-bcffc21e405f.png)

Não deve ser muito difícil resolver, posso cuidar disso, mas gostaria de ajuda de quem puder testar em outros tamanhos de tela só pra ter certeza de que não vai quebrar. Apesar de que, me parece que isso só tá acontecendo no iPhone 5S ou inferior por causa da tela mais estreita. A maioria dos smartphones hoje tem uma largura de tela maior, então não deve ser problema.

**Comment by esasse** [comment]
Já tinha uma issue reportando este problema. Não sei se ainda está aberta.

**Comment by alissonbrunosa** [comment]
Usei o simulador do Chrome para dispositivos e somente no Iphone 5 aconteceu esse problema.

**Comment by dodops** [comment]
Testei aqui em um Android. 

O problema acontece na página "/jobs". Na home page está ok. Vou dar uma olhada

**Comment by lccezinha** [comment]
@matheusml fechar esse cara  ? Fixed #91

**Comment by matheusml** [comment]
Boa @lccezinha
